name: hashi-demo-app
on: [push]
jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        registry: ${{ secrets.DOCKERHUB_REGISTRY }}
    - run: echo "DOCKER_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
    - uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.workflow }}:${{ env.DOCKER_TAG }}